IBM/carbon-ui-builder

src/assets/component-icons/tag.svg, src/fragment-components/a-tag.tsx, src/fragment-components/index.ts
=> Add tag component

src/assets/component-icons/accordion-item.svg, src/assets/component-icons/accordion.svg, src/components/adder.tsx, src/components/index.ts, src/fragment-components/a-component.tsx, src/fragment-components/accordion/a-accordion-item.tsx, src/fragment-components/accordion/a-accordion.tsx, src/fragment-components/index.ts
=> Add accordion component

src/fragment-components/a-numberinput.tsx, src/fragment-components/a-textarea.tsx, src/fragment-components/a-textinput.tsx, src/fragment-components/tiles/a-clickable-tile.tsx, src/fragment-components/tiles/a-expandable-tile.tsx, src/fragment-components/tiles/a-radio-tile-group.tsx, src/fragment-components/tiles/a-radio-tile.tsx, src/fragment-components/tiles/a-selectable-tile-group.tsx, src/fragment-components/tiles/a-selectable-tile.tsx, src/fragment-components/tiles/a-tile-fold.tsx, src/fragment-components/tiles/a-tile.tsx, src/fragment-components/tiles/tile-morphism.tsx
I think we merged in the wrong order, tiles were missing the mapping. have added them below
=> updated Tiles Type mapping

src/fragment-components/a-progress-indicator.tsx
Angular exports shows [Object object] instead of actual json for progress indicator
=> Fix angular export for progress indicator

src/fragment-components/a-button.tsx, src/fragment-components/accordion/a-accordion-item.tsx, src/fragment-components/index.ts
closes https://github.com/IBM/carbon-components-builder/issues/102
closes https://github.com/IBM/carbon-components-builder/issues/103
=> Add missing input names for button and accordian

src/fragment-components/a-button.tsx, src/ui-fragment/src/components/ui-button.tsx
=> Add size to button

src/fragment-components/a-toggle.tsx
This pull request resolves https://github.com/IBM/carbon-ui-builder/issues/135
=> fix: "Toggle" commponent react export doesn't update state 

src/components/notification.tsx
This Pull Request resolves #168
=> Fix Notification Component to make it to the front

src/routes/edit/share-options/exports/export-modal.tsx
Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
closes https://github.com/IBM/carbon-ui-builder/issues/182
=> fix: tooltip text in the JSON export tab

src/fragment-components/accordion/a-accordion-item.tsx, src/fragment-components/accordion/a-accordion.tsx, src/routes/edit/share-options/exports/frameworks/angular-fragment.ts
Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
closes https://github.com/IBM/carbon-ui-builder/issues/156
=> feat: Add missing Accordion attributes for angular

package-lock.json, src/routes/dashboard/fragment-wizard/create-fragment-modal.tsx
- Related Issue #145 
- Closes #
This PR replaces the current checkboxes in the `New fragment` dialog box with `Radio buttons`.
- The `New fragment` dialog box currently uses checkboxes to select one template. We could use Radio buttons in place of the checkboxes which would be more suitable for the current usage.
- Extra attention has to be paid to the `Tile Group` section in `create-fragment-modal.tsx` file. Also, the usage of Radio buttons replaces the current checkboxes (`selection-tile.tsx` file).
=> fixed new fragment dialog box to show radiobuttons

src/fragment-components/a-code-snippet.tsx
Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
- Closes https://github.com/IBM/carbon-ui-builder/issues/218
=> fix: Code snippet monaco editor not working

src/routes/from-json/index.tsx
Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
closes https://github.com/IBM/carbon-ui-builder/issues/221
=> fix: Remove disc from accordion item preview

src/sdk/src/draggable-list.tsx
=> fix: Align trash button top-right of the icon

src/ui-fragment/src/components/ui-grid.tsx
Uses flex grid instead of CSS in preview
=> fix: use flex grid instead of CSS grid

src/sdk/src/fragment-components/a-combobox.tsx, src/sdk/src/fragment-components/a-dropdown.tsx, src/sdk/src/fragment-components/a-numberinput.tsx, src/sdk/src/fragment-components/a-searchinput.tsx, src/sdk/src/fragment-components/a-text-area.tsx, src/sdk/src/fragment-components/a-text-input.tsx, src/sdk/src/styles.ts
- Related Issue #104 
- Closes #104
=> Inputs shouldn't take input in canvas view #104

src/context/fragments-context-helper.ts, src/routes/dashboard/fragment-wizard/generate-new-fragment.ts, src/routes/dashboard/fragment-wizard/import-json-modal.tsx
=> fix: Allow microlayouts to be imported via JSON

src/sdk/src/fragment-components/a-fragment.tsx
=> fix: Make fragments inline to match preview

sdk/react/src/lib/components/settings-context-pane.tsx
* Prevents checkbox style from leaking in settings context pane
=> fix: prevent checkbox inline style from leaking

app/src/routes/edit/share-options/exports/frameworks/angular/latest/fragment.ts, app/src/routes/edit/share-options/exports/frameworks/react/latest/fragment.ts
* Latest angular export matches CCA@v5 (Angular 14)
* Latest react export is same as Builder (React 18)
=> fix: update latest export codes 
